### PR TITLE
df.sort is depreciated

### PR DESCRIPTION
**Pull request by epratheeban**
Hi Herve,

df.sort() changed to df.sort_values() for pandas version >= 0.17

Thanks
Pratheeban

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks. However, I think `setup.py` also needs to be updated to clearly state its pandas dependency (e.g. >= 0.17).

**Comment by epratheeban** [comment]
Yes, I thought of this. I will make the change now in` setup.py`

**Comment by crhan** [comment]
great job, I get the error with panda version 0.20.3:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-4e9e77068764> in <module>()
----> 1 face_tracks, embeddings = clustering.model.preprocess('../../pyannote-data/TheBigBangTheory.embedding.txt')
      2 face_tracks.get_timeline()

/home/ruohan.chen/.anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/video/face/clustering.py in preprocess(self, embedding)
     73         data = read_table(embedding, delim_whitespace=True,
     74                           header=None, names=names)
---> 75         data.sort(columns=['track', 'time'], inplace=True)
     76         starting_point = Annotation(modality='face')
     77         for track, segment in data.groupby('track').apply(self._to_segment).iteritems():

/home/ruohan.chen/.anaconda3/envs/pyannote/lib/python3.5/site-packages/pandas/core/generic.py in __getattr__(self, name)
   2968             if name in self._info_axis:
   2969                 return self[name]
-> 2970             return object.__getattribute__(self, name)
   2971 
   2972     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'sort'
```

**Comment by hbredin** [comment]
Closing as this was integrated in #27

**Pull request closed without merging**
